repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: Format dotnet files
        entry: dotnet format -v n
        language: system
        files: '\.(cs|csproj|sln)$'
        stages: [pre-commit]
