repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: Format dotnet files
        entry: dotnet format -v n
        language: system
        files: '\.(cs|vb|csproj|vbproj|json|xml|sln)$'
