repos:
  - repo: local
    hooks:
      - id: dotnet-format
        name: Format dotnet files
        entry: dotnet format
        language: system
        files: '\.(csproj|sln)$'
        stages: [pre-commit]
