name: Publish to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - '**/*.csproj'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.202'
      
      - name: Configure NuGet for GitHub Packages
        run: |
          dotnet nuget add source \
            --username zone016 \
            --password "${{secrets.GITHUB_TOKEN}}" \
            --store-password-in-clear-text \
            --name "github" \
            "https://nuget.pkg.github.com/zone016/index.json"

      - name: Global restore
        run: dotnet restore

      - name: Global pack build
        run: dotnet pack -c Release --no-restore --output ./packages

      - name: NuGet publish
        run: dotnet nuget push "./packages/*.nupkg" --source "github" --skip-duplicate
