name: Publish to GitHub Packages

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.csproj'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      
      - name: Configure NuGet for GitHub Packages
        run: |
          dotnet nuget add source --username zone016 --password ${{secrets.GITHUB_TOKEN}} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/zone016/index.json"

      - name: Build and publish .csproj modifications
        run: |
          for csproj in $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.csproj$'); do
            dotnet pack $csproj -c Release --output ./nupkgs
            dotnet nuget push "./nupkgs/*.nupkg" --source "github"
          done
